# Autogenerated wrapper script for legate_jl_wrapper_jll for aarch64-linux-gnu-cxx11-cuda+12.8-julia_version+1.11.1-cuda_platform+jetson
export liblegate_jl_wrapper

using legate_jll
using libcxxwrap_julia_jll
using CompilerSupportLibraries_jll
using CUDA_Runtime_jll
JLLWrappers.@generate_wrapper_header("legate_jl_wrapper")
JLLWrappers.@declare_library_product(liblegate_jl_wrapper, "liblegate_jl_wrapper.so.0.0.1")
function __init__()
    JLLWrappers.@generate_init_header(legate_jll, libcxxwrap_julia_jll, CompilerSupportLibraries_jll, CUDA_Runtime_jll)
    JLLWrappers.@init_library_product(
        liblegate_jl_wrapper,
        "lib/liblegate_jl_wrapper.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
